version: "3"

services:
  db:
    container_name: housing_db
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: real_estates
      MYSQL_USERNAME: admin
      MYSQL_ROOT_PASSWORD: nimda
    #healthcheck:
     # test: mysqladmin ping -h localhost --user admin --password=nimda
      #timeout: 5s
      #retries: 10
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - real_estates_network

  adminer:
      image: adminer
      restart: always
      ports:
        - "9000:8080"
      networks:
        - real_estates_network

volumes:
  mysql-data:

networks:
  real_estates_network:
    driver: bridge